// Generates lib/wc/third-allocation.ts: FIFA's official allocation of the eight
// best third-placed teams into the Round of 32, one entry per qualifying-group
// combination. Sourced from Wikipedia (which mirrors FIFA's published table).
// Re-run with: bun run scripts/gen-third-allocation.ts
import { writeFileSync } from "node:fs";
import * as cheerio from "cheerio";

const URL = "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_knockout_stage";
// Column order of the "1X vs" winner headers in the source table.
const WINNERS = ["A", "B", "D", "E", "G", "I", "K", "L"];
// Our R32 slot → the group winner that occupies its non-third side (from R32_SLOTS).
const SLOT_WINNER: [number, string][] = [
  [2, "E"],
  [5, "I"],
  [7, "A"],
  [8, "L"],
  [9, "D"],
  [10, "G"],
  [13, "B"],
  [15, "K"],
];

const html = await fetch(URL, { headers: { "User-Agent": "Mozilla/5.0" } }).then((r) => r.text());
const $ = cheerio.load(html);
const t = $("table.wikitable").toArray()[0];

const table: Record<string, string> = {};
for (const tr of $(t).find("tr").toArray()) {
  const cells = $(tr)
    .find("th,td")
    .toArray()
    .map((c) => $(c).text().replace(/\s+/g, " ").trim());
  const groups = cells.filter((c) => /^[A-L]$/.test(c));
  const thirds = cells.filter((c) => /^3[A-L]$/.test(c)).map((c) => c[1]);
  if (groups.length !== 8 || thirds.length !== 8) continue; // header / malformed
  const winnerThird = Object.fromEntries(WINNERS.map((w, i) => [w, thirds[i]]));
  const key = [...groups].sort().join("");
  table[key] = SLOT_WINNER.map(([, w]) => winnerThird[w]).join("");
}

// Validate every row structurally: the eight assigned thirds are exactly the
// qualifying groups (a permutation of the key), and no third faces the winner of
// its own group — FIFA's defining constraint. Catches a source-table column
// reorder that a row count or single spot-check would silently pass.
for (const [combo, val] of Object.entries(table)) {
  if ([...val].sort().join("") !== combo)
    throw new Error(`row ${combo}: thirds ${val} are not a permutation of the qualifying groups`);
  [...val].forEach((g, i) => {
    if (g === SLOT_WINNER[i]?.[1])
      throw new Error(`row ${combo}: 3rd-${g} faces its own group winner`);
  });
}
const n = Object.keys(table).length;
const slotIdx = SLOT_WINNER.findIndex(([s]) => s === 8); // the Group L winner's slot
// Anchor against The Athletic's published bracket (winner L → Senegal=I; → DR Congo=K).
if (n !== 495 || table["ABDEFGIL"]?.[slotIdx] !== "I" || table["BDEFGIKL"]?.[slotIdx] !== "K")
  throw new Error("verification failed");
console.log(`verified ${n} combinations`);

const slotOrder = SLOT_WINNER.map(([s]) => s);
const slotWinners = SLOT_WINNER.map(([, w]) => w);
const body = `// AUTO-GENERATED by scripts/gen-third-allocation.ts — do not edit by hand.
// FIFA's official Round-of-32 allocation of the eight best third-placed teams.
// Key: the eight qualifying groups, sorted (e.g. "ABDEFGIL"). Value: the group
// whose third-placed team fills each R32 third-slot, in SLOT order [${slotOrder.join(", ")}]
// (i.e. facing group winners ${slotWinners.join(", ")} respectively).
// Source: ${URL}
export const THIRD_SLOT_ORDER = [${slotOrder.join(", ")}] as const;
export const THIRD_ALLOCATION: Record<string, string> = ${JSON.stringify(table, null, 2)};
`;
writeFileSync("lib/wc/third-allocation.ts", body);
console.log("wrote lib/wc/third-allocation.ts");
