// Generates lib/wc/third-allocation.ts: FIFA's official allocation of the eight
// best third-placed teams into the Round of 32, one entry per qualifying-group
// combination. Sourced from Wikipedia (which mirrors FIFA's published table).
// Re-run with: bun run scripts/gen-third-allocation.ts
import { writeFileSync } from "node:fs";
import * as cheerio from "cheerio";

const URL = "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_knockout_stage";
// Column order of the "1X vs" winner headers in the source table.
const WINNERS = ["A", "B", "D", "E", "G", "I", "K", "L"];
// Our R32 slot → the group winner that occupies its non-third side (from R32_SLOTS).
const SLOT_WINNER: [number, string][] = [
  [2, "E"],
  [5, "I"],
  [7, "A"],
  [8, "L"],
  [9, "D"],
  [10, "G"],
  [13, "B"],
  [15, "K"],
];

const html = await fetch(URL, { headers: { "User-Agent": "Mozilla/5.0" } }).then((r) => r.text());
const $ = cheerio.load(html);
const t = $("table.wikitable").toArray()[0];

const table: Record<string, string> = {};
for (const tr of $(t).find("tr").toArray()) {
  const cells = $(tr)
    .find("th,td")
    .toArray()
    .map((c) => $(c).text().replace(/\s+/g, " ").trim());
  const groups = cells.filter((c) => /^[A-L]$/.test(c));
  const thirds = cells.filter((c) => /^3[A-L]$/.test(c)).map((c) => c[1]);
  if (groups.length !== 8 || thirds.length !== 8) continue; // header / malformed
  const winnerThird = Object.fromEntries(WINNERS.map((w, i) => [w, thirds[i]]));
  const key = [...groups].sort().join("");
  table[key] = SLOT_WINNER.map(([, w]) => winnerThird[w]).join("");
}

const n = Object.keys(table).length;
console.log(`parsed ${n} combinations`);
const slotIdx = SLOT_WINNER.findIndex(([s]) => s === 8);
console.log(`check ABDEFGIL → winner L gets 3rd of: ${table["ABDEFGIL"]?.[slotIdx]} (expect I)`);
console.log(`check BDEFGIKL → winner L gets 3rd of: ${table["BDEFGIKL"]?.[slotIdx]} (expect K)`);
if (n !== 495 || table["ABDEFGIL"]?.[slotIdx] !== "I") throw new Error("verification failed");

const body = `// AUTO-GENERATED by scripts/gen-third-allocation.ts — do not edit by hand.
// FIFA's official Round-of-32 allocation of the eight best third-placed teams.
// Key: the eight qualifying groups, sorted (e.g. "ABDEFGIL"). Value: the group
// whose third-placed team fills each R32 third-slot, in SLOT order [2,5,7,8,9,10,13,15]
// (i.e. facing group winners E, I, A, L, D, G, B, K respectively).
// Source: ${URL}
export const THIRD_SLOT_ORDER = [2, 5, 7, 8, 9, 10, 13, 15] as const;
export const THIRD_ALLOCATION: Record<string, string> = ${JSON.stringify(table, null, 0)
  .replace(/","/g, '",\n  "')
  .replace(/^\{"/, '{\n  "')
  .replace(/"\}$/, '",\n}')};
`;
writeFileSync("lib/wc/third-allocation.ts", body);
console.log("wrote lib/wc/third-allocation.ts");
